Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -183,6 +183,27 @@ jobs:
             export ARTIFACTDIR=`pwd`/buildartifacts
             git config --global --add safe.directory /github/workspace/sources/nuttx
             git config --global --add safe.directory /github/workspace/sources/apps
+
+            # Validate the defconfig files
+            pushd sources/nuttx
+            testfile=tools/ci/testlist/${{matrix.boards}}.dat
+            echo Validating targets in $testfile
+            testlist=`grep -v -E "^(-|#)|^[C|c][M|m][A|a][K|k][E|e]" $testfile || true`          
+            for line in $testlist; do
+              firstch=${line:0:1}
+              if [ "X$firstch" == "X/" ]; then
+                dir=`echo $line | cut -d',' -f1`
+                list=`find boards$dir -name defconfig | cut -d'/' -f4,6`
+                for i in ${list}; do
+                  echo ./tools/refresh.sh --silent $i
+                  ./tools/refresh.sh --silent $i
+                done
+              fi
+            done
+            popd
+            # TODO: Check for failure
+
+            # Build the targets
             cd sources/nuttx/tools/ci
             if [ "X${{matrix.boards}}" = "Xcodechecker" ]; then
                 ./cibuild.sh -c -A -N -R --codechecker testlist/${{matrix.boards}}.dat
